name: Inventory CI (one repo / service tag)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch: {}   # 버튼으로도 실행 가능

permissions:
  contents: read

jobs:
  build-and-push-inventory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4

      - run: chmod +x ./gradlew

      # (옵션) CI 전용 설정파일이 필요하면 Secrets로 생성
      # - name: Create application-ci.yml
      #   run: |
      #     mkdir -p src/main/resources
      #     echo "${{ secrets.APP_CI_YML }}" > src/main/resources/application-ci.yml

      - name: Build inventory jar
        run: ./gradlew clean test bootJar -Dspring.profiles.active=ci

      - name: Set image tags
        id: vars
        run: |
          SHA=${GITHUB_SHA::7}
          echo "IMAGE=hysungzzang/sampoom" >> $GITHUB_OUTPUT
          echo "TAG_SHA=inventory-${SHA}"  >> $GITHUB_OUTPUT
          echo "TAG_LATEST=inventory-latest" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # buildx가 RST_STREAM 날릴 때가 있어요 → 아래 옵션들이 비교적 안정적
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            network=host

      - name: Build & Push (inventory)
        uses: docker/build-push-action@v6
        env:
          BUILDKIT_PROGRESS: plain
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true          # 초기엔 캐시끄기(문제줄이기). 안정화 후 제거 가능
          provenance: false       # 일부 환경에서 GRPC 이슈 완화
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_SHA }}
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG_LATEST }}
